platform :ios, '7.0'


pod 'DPAnimators', :path => '~/Development/LocalPods/DPAnimators'
pod 'DPKit-UIView', :path => '~/Development/LocalPods/DPKit-Suite/DPKit-UIView'
pod 'DPKit-Utils', :path => '~/Development/LocalPods/DPKit-Suite/DPKit-Utils'

pod 'VCTransitionsLibrary'