platform :ios, '7.0'


pod 'AutoCoding'
pod 'UIColorCategories'
pod 'NSObject+AutoDescription'
#pod 'TestFlightSDK'

pod 'CALayer-DPUtils'
pod 'DPCollectionView'

pod 'DPKit-Utils', :path => '~/Development/LocalPods/DPKit-Suite/DPKit-Utils'
pod 'DPTransitions', :path => '~/Development/LocalPods/DPTransitions'
pod 'DPKit-UIView', :path => '~/Development/LocalPods/DPKit-Suite/DPKit-UIView'


