platform :ios, '7.0'


pod 'AutoCoding'
pod 'UIColorCategories'
pod 'NSObject+AutoDescription'
#pod 'TestFlightSDK'
pod 'UIAlertView+Blocks'
pod 'AFNetworking'

pod 'CALayer-DPUtils'
pod 'DPCollectionView'

pod 'DPKit-Utils', :path => '~/Development/LocalPods/DPKit-Suite/DPKit-Utils'
pod 'DPTransitions', :path => '~/Development/LocalPods/DPTransitions'
pod 'DPKit-UIView', :path => '~/Development/LocalPods/DPKit-Suite/DPKit-UIView'

pod 'DPAnimators', :path => '~/Development/LocalPods/DPAnimators'

pod 'AFOAuth2Client', :git => 'https://github.com/mlwelles/AFOAuth2Client'

